# Generated by Django 5.2.7 on 2026-06-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userbankaccount",
            old_name="bath_date",
            new_name="birth_date",
        ),
    ]
