# Generated by Django 5.2.7 on 2025-10-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "balance_after_transtion",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "transition_type",
                    models.IntegerField(
                        choices=[
                            (1, "Deposite"),
                            (2, "Withdrawal"),
                            (3, "Loan"),
                            (4, "Loan Paid"),
                        ],
                        null=True,
                    ),
                ),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
                ("loan_approve", models.BooleanField(default=False)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="accounts.userbankaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["time_stamp"],
            },
        ),
    ]
