# Generated by Django 5.2.7 on 2026-06-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="transition_type",
            new_name="transaction_type",
        ),
    ]
