# Generated by Django 5.2.7 on 2026-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_rename_transition_type_transaction_transaction_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="balance_after_transtion",
            new_name="balance_after_transaction",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.IntegerField(
                choices=[
                    (1, "Deposit"),
                    (2, "Withdrawal"),
                    (3, "Loan"),
                    (4, "Loan Paid"),
                    (5, "Money Send"),
                    (6, "Money Received"),
                ],
                null=True,
            ),
        ),
    ]
